spring:
  datasource:
    url: jdbc:mysql://localhost:3306/builddream?&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
server:
  port: 8085